type: slave
env: "production" # Must be set to the same value as the master.
slave_setting:
  port: 50051
  # certificate:
  #   enabled: true
  #   slave_cert: "certs/slave.crt"
  #   slave_key: "certs/slave.key"
  encrypt:
    enabled: true
    encrypt_id: "encryptStaticCBC"
encrypts:
    # The id is required, and it must be unique.
  - id: "encryptStaticCBC"
    # Supported types are `staticCBC`, `staticCFB`, `staticCTR`.
    type: "staticCBC"
    key: "must override"
logging:
  output:
    # - type: "stdout"
    #   format: "text"
    #   level: "warn"
    #   # If enabled_env is not set, it will be enabled all environments.
    #   enabled_env:
    #     - "production"
    - type: "file"
      filename: "logs/app.log"
      format: "text"
      level: "warn"
    # - type: "tcp"
    #   address: "127.0.0.1:5000"
    #   format: "json"
    #   level: "warn"
clock:
  fake: 
    # If enabled_env is not set, it will be enabled all environments.
    enabled: true
    time: "2021-01-01T00:00:00Z"
  # The default value is `2006-01-02T15:04:05Z`.
  format: "2006-01-02T15:04:05Z"
language:
  default: "en"
# The one below takes precedence over the one above.
# The bottom one takes precedence.
override:
  - type: "file"
    # The file_type is required to load the file, supported types are `yaml`, `json`.
    file_type: "yaml"
    path: "bloader/static_encrypt.yaml"
    partial: true
    vars:
      - key: encrypts[0].key
        value: "encrypt_key"
  # - type: "file"
  #   file_type: "yaml"
  #   path: "bloader/local_override.yaml"
  #   # If enabled_env is not set, it will be enabled all environments.
  #   enabled_env:
  #     - "local"
  # - type: "file"
  #   file_type: "yaml"
  #   path: "bloader/production_override.yaml"
  #   enabled_env:
  #     - "production"
  # - type: "static"
  #   key: "auth[0].oauth2.auth_url"
  #   value: "http://localhost:8080/oauth2/authorize"
  #   enabled_env:
  #     - "local"
  # - type: "static"
  #   key: "auth[0].oauth2.token_url"
  #   value: "http://localhost:8080/oauth2/token"
  #   enabled_env:
  #     - "local"
