type: slave
env: "production" # Must be set to the same value as the master.
slave_setting:
  port: 50051
  certificate:
    enabled: true
    slave_cert: "certs/slave.crt"
    slave_key: "certs/slave.key"
  encrypt:
    enabled: true
    encrypt_id: "encryptStaticCBC"
logging:
  output:
    - type: "stdout"
      format: "text"
      level: "warn"
      # If enabled_env is not set, it will be enabled all environments.
      enabled_env:
        - "local"
    # - type: "file"
    #   filename: "logs/app.log"
    #   format: "text"
    #   level: "debug"
    # - type: "tcp"
    #   address: "127.0.0.1:5000"
    #   format: "json"
    #   level: "warn"
clock:
  fake: 
    # If enabled_env is not set, it will be enabled all environments.
    enabled: true
    time: "2021-01-01T00:00:00Z"
  # The default value is `2006-01-02T15:04:05Z`.
  format: "2006-01-02T15:04:05Z"
language:
  default: "en"
# The one below takes precedence over the one above.
# The bottom one takes precedence.
override: []
  # - type: "file"
  #   # The file_type is required to load the file, supported types are `yaml`, `json`.
  #   file_type: "yaml"
  #   path: "bloader/partial_override.yaml"
  #   partial: true
  #   vars:
  #     - key: auth[0].oauth2.client_id
  #       value: "auth.clientId"
  #     - key: auth[0].oauth2.client_secret
  #       value: "auth.clientSecret"
  #   # If enabled_env is not set, it will be enabled all environments.
  #   # enabled_env:
  # - type: "file"
  #   file_type: "yaml"
  #   path: "bloader/local_override.yaml"
  #   # If enabled_env is not set, it will be enabled all environments.
  #   enabled_env:
  #     - "local"
  # - type: "file"
  #   file_type: "yaml"
  #   path: "bloader/production_override.yaml"
  #   enabled_env:
  #     - "production"
  # - type: "static"
  #   key: "auth[0].oauth2.auth_url"
  #   value: "http://localhost:8080/oauth2/authorize"
  #   enabled_env:
  #     - "local"
  # - type: "static"
  #   key: "auth[0].oauth2.token_url"
  #   value: "http://localhost:8080/oauth2/token"
  #   enabled_env:
  #     - "local"
