# Site Information
title: "Bloader - Benchmark Test Tool 🚀"
description: "A modern and flexible load testing tool for your benchmarking needs."
author: "Hayashi Kenta"
lang: "en"
timezone: "UTC"

# Theme
remote_theme: "pmarsceill/just-the-docs"

# Plugins
plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Navigation Bar
collections:
  docs:
    output: true

# Sidebar Navigation
just_the_docs:
  aux_links:
    "GitHub Repository": "https://github.com/ablankz/bloader"
  search_enabled: true
  search_tokenizer_separator: /[\s\-/]+/

# SEO Optimization
seo:
  description: "Modern and flexible benchmarking tool documentation."
  keywords: "Benchmark, Load Testing, YAML Configuration, gRPC, Flexible Tool"
  twitter_card: "summary_large_image"

# Sitemap
sitemap:
  changefreq: "weekly"
  priority: "0.8"

# Exclude Files from Build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
