name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
      - 'releases/**'
  pull_request:
    branches:
      - main
      - develop
      - 'releases/**'

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yaml
  test:
    name: Test
    uses: ./.github/workflows/test.yaml
    permissions:
      contents: write
      actions: read
      checks: write
      pull-requests: write