name: Test

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test-go:
    name: Test go files
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
      checks: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install gotestsum
        run: |
          go install gotest.tools/gotestsum@latest
      - name: Run tests and generate JUnit report, test coverage
        run: |
          go clean -testcache
          "gotestsum --junitfile report.xml --format testdox --  -cover -covermode=atomic -coverprofile=coverage.out ./... -race"
      - name: Upload test report and coverage
        uses: actions/upload-artifact@v4
        with:
          name: junit-test-report-and-coverage
          path: |
            report.xml
            coverage.out
      - name: Test Report Summary
        if: success() || failure()
        uses: dorny/test-reporter@v1
        with:
          name: Tests
          path: "*.xml"
          reporter: java-junit
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

